### ISSUE TITLE
Slash command support

### ISSUE THREAD

**Issue by jchristgit** [jchristgit/nosedrum#14]
Per discussion in #1 with @Bentheburrito.

> I think Slash Commands are different enough to warrant their own behaviour imo. I have a rudimentary slash command handler on another bot that I could clean up and use as a starting point? Also, should I open a separate issue for further discussion?

My current idea:

- Implement a new `Nosedrum.SlashCommand` behaviour.
- Implement an interaction handler (possibly some kind of merge between `Nosedrum.Invoker` and `Nosedrum.Storage`, since the Invoker is less useful here) to dispatch, store and manage commands.

**Comment by Bentheburrito** [comment]
I noticed Discord recently changed terminology to "Application Commands" https://discord.com/developers/docs/interactions/application-commands - which include User/Message commands in addition to Slash Commands. Are these two new types of commands something you see Nosedrum supporting?

**Comment by jchristgit** [comment]
Hmm, from a quick glance over it, it looks like these are pretty much just built on top of the existing slash commands? Interesting, I haven't seen these before. Yeah, I think we should possibly name it something like `Nosedrum.ApplicationCommand` then, and integrate with that

**Comment by Bentheburrito** [comment]
Cool! I'm happy to get started on this then :)

**Comment by jchristgit** [comment]
Awesome, I'll assign you then, Thank you!
