### ISSUE TITLE
Improve Interaction Handling

### ISSUE THREAD

**Issue by Bentheburrito** [jchristgit/nosedrum#24]
Hi @jchristgit! A month or two ago someone in the nostrum discord mentioned a design flaw with how Application Commands are run, and indeed I think I was a bit naive when I wrote [this part](https://github.com/jchristgit/nosedrum/blob/9af597a26f3d3de09c8184f292a18b35bc47477c/lib/nosedrum/interactor/dispatcher.ex#L145C45-L146) of `Nosedrum.Interactor.Dispatcher` specifically:
```elixir
  @impl true
  def handle_cast({:handle, %Interaction{data: %{name: name}} = interaction}, commands) do
    with {:ok, module} <- Map.fetch(commands, name) do
      response = module.command(interaction)
      Interactor.respond(interaction, response)
    end

    {:noreply, commands}
  end
```
Currently, if a user's `command/1` callback errors, it looks like it takes down the dispatcher with it. 

I think it would be better to run the body of that `with` inside a `Task`, probably using a `Task.Supervisor` - and more specifically [`Task.Supervisor.start_child/5`](https://hexdocs.pm/elixir/1.13/Task.Supervisor.html#start_child/5). Although, I see in #20 you might care about knowing the success of the response, in which case maybe [`Task.Supervisor.async_nolink/5`](https://hexdocs.pm/elixir/1.13/Task.Supervisor.html#async_nolink/5) would be better? What do you think? Any other approach you would recommend to make the dispatcher more resilient to crashes caused by running a user's application command?

I have some free time over the next week and could have a PR up soon if this approach looks good to you :)

**Comment by Bentheburrito** [comment]
Actually, better yet, instead of creating a Task Supervisor, maybe the caller process spawned by nostrum can run the `with` body by moving it to [`handle_interaction/1`](https://github.com/jchristgit/nosedrum/blob/9af597a26f3d3de09c8184f292a18b35bc47477c/lib/nosedrum/interactor/dispatcher.ex#L32). I think we'd just have to convert that `cast` to a `call` that takes the interaction command name and returns the command module

**Comment by jchristgit** [comment]
Hello!

> Actually, better yet, instead of creating a Task Supervisor, maybe the caller process spawned by nostrum can run the with body by moving it to [handle_interaction/1](https://github.com/jchristgit/nosedrum/blob/9af597a26f3d3de09c8184f292a18b35bc47477c/lib/nosedrum/interactor/dispatcher.ex#L32). I think we'd just have to convert that cast to a call that takes the interaction command name and returns the command module

I think this is the preferable way to go.

Nostrum's consumer spawns a process for each gateway event, so this seems like the logical step to me. That way, the interactor is also harder to overload (for very big bots) if all it does is provide synchronized access to the storage.

Perhaps we should rename it in that case, though? What do you think?

**Comment by Bentheburrito** [comment]
Awesome! I can work on making this change then. I agree with renaming `Interactor`, though I'm historically a horrible namer :P Maybe we rename it to `Storage` and move it under the `ApplicationCommand` module? The full path would then be `Nosedrum.ApplicationCommand.Storage`. Open to thoughts about this of course.

Do you think we should rename `Dispatcher` too?

**Comment by Bentheburrito** [comment]
Ohh gotcha, that makes sense. I can definitely move the modules around in the PR then!
